services:
  backend:
    build:
      context: ./spring-boot-jpa
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./vue-3-crud
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - PORT=80
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge