name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tag push that matches v*, e.g., v1.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build and Test with Maven
      run: mvn -B verify --file spring-boot-jpa/pom.xml

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # Insert Changelog Body
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      # Here we have insert this variable
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Add steps to upload artifacts like code, documentation, sources, etc.
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spring-boot-jpa/spring-boot-jpa/target/flashcard-spring-boot-${{ github.ref }}.jar
          asset_name: flashcard_backend.jar
          asset_content_type: application/jar
