name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # Specify your JDK version
        distribution: 'adopt'  # Specify JDK distribution

    - name: Build with Maven
      run: mvn -B package --file spring-boot-jpa/pom.xml

    - name: Run tests
      run: mvn test --file spring-boot-jpa/pom.xml
